// Generated by scripts/optimize-images.mjs. Do not edit; run `npm run images`.
import type { ImageAsset } from '../types';

export const imageManifest: Record<string, ImageAsset[]> = {
  "about-home-stay": [
    {
      "id": "about-home-stay",
      "label": "About home stay",
      "src": "/images/about-home-stay-1e83b736",
      "widths": [
        320,
        640,
        1024,
        1600,
        2400
      ],
      "width": 2400,
      "height": 1600,
      "blur": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAAAQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZgCsAYyAfjpp9iidRO3huAD8xe8Wbr8YI3uUlHyTs1Rav7DnBZNChOJM1u7ab4kVvweGriHbQYmdOsu9Q0ALblG9s3HfUBfJbDiT8O7m3BUrxuhC4LNHQZRH3DfvCzD+gX0L3xLyUk/Nl9Pwe2A37aLc/AJ90bGwZfz95pt5owOvGibmAGQ04ls46gAA"
    }
  ],
  "double-bedroom": [
    {
      "id": "double-bedroom-1",
      "label": "Double bedroom",
      "src": "/images/double-bedroom-1-d90fb77a",
      "widths": [
        320,
        640,
        1024,
        1600,
        2400
      ],
      "width": 2400,
      "height": 1600,
      "blur": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JaAC7Ef/gOa/9lgtesFsUcriCAAD06gT7gbT0U3UzP6uOrJ+h31C30obJCENXmxalXArzY27IcTi2uvTaf69aWixVztWvK5b4F8l5dGcwjuqJU/pK77F8AxWYKSB8j7/WBblPc0e8QPjI1yL5B3SGOS4Dep6TZ8HnaWsc1YsmIzgA"
    },
    {
      "id": "double-bedroom-2",
      "label": "Double bedroom",
      "src": "/images/double-bedroom-2-169731e0",
      "widths": [
        320,
        640,
        1024,
        1600,
        2400
      ],
      "width": 2400,
      "height": 1600,
      "blur": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JYwC7AB6V56RhEocJUtk/2CnEAAD8XWu8KhTxkXshT24D9Vzugkbz2W6vkpmATa9+J4WDz0sY0iKUBiEt9YAeXV9m6R3OJsPBVadCbTf/HzNSk3O6p9ecgW/r29R3Kxj4NZa2JlA2neHjFDzWrsTCuYHBZmX4OZwyXMkWR0n2EgAEy9HVhAAA"
    },
    {
      "id": "double-bedroom-bathroom-1",
      "label": "Double bedroom bathroom",
      "src": "/images/double-bedroom-bathroom-1-0327debf",
      "widths": [
        320,
        640,
        1024,
        1600,
        2400
      ],
      "width": 2400,
      "height": 1600,
      "blur": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAACwAwCdASoYABAALrV2u12jqampiYC0SyAFp0IvduQpHaohx4TQAADeZ33NohGeA107I1dXJiypq0X4ozeTymbDzv/5rS0umLmXsj2ChEUy89GDKaqIQPAm05wRLME5l4539TjU5VoGmWdi2/v+sROjVT8sjrJXFkBQ3qNqKGANpbEAAAA="
    },
    {
      "id": "double-bedroom-bathroom-2",
      "label": "Double bedroom bathroom",
      "src": "/images/double-bedroom-bathroom-2-0f8b931b",
      "widths": [
        320,
        640,
        1024,
        1600,
        2400
      ],
      "width": 2400,
      "height": 1600,
      "blur": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAABQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JZQC7AYv+3Ug0o12cNVWOhrJAAP5mX38A5qn64F+vOM3htishOiHkp/tWkfuNtWfGzOUPWdO6yjP/cqDDTyiGPkzSm+XQyfsNxM1Swgwvd/HmpNZlXPxvY+dNy8ItlThr1S7dfFqVdHg9FmQf4mzZTs3yAA=="
    },
    {
      "id": "double-bedroom-study-table",
      "label": "Double bedroom study table",
      "src": "/images/double-bedroom-study-table-f91b557d",
      "widths": [
        320,
        640,
        1024,
        1600,
        2400
      ],
      "width": 2400,
      "height": 1600,
      "blur": "data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JbACdMoAC2XEnk2+eoAVzJ5LNQAD+70mOr8UM5zjoX0Q0Cm5E7oqVKMacXWSyYBzYqzIBnWxnuu9deibt1Q4esWIImsqzf0EHd1oshSCBdfjWVVZP/9kEIpzqvN2pSCQGH6Hddl9q8AAA"
    }
  ],
  "family-room": [
    {
      "id": "family-room-1",
      "label": "Family room",
      "src": "/images/family-room-1-93c1eddb",
      "widths": [
        320,
        640,
        1024,
        1600,
        2400
      ],
      "width": 2400,
      "height": 1600,
      "blur": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAADwAwCdASoYABAAPu1iqU2ppaOiMAgBMB2JZgCw7BL0dOIImNrzfMwAAPOpLFjplHPHf+sWWX33Pc8I3CUZJ3LKmdYpmjdRIj8tFBBKqyCLe9etLc3CfViWR8XEGvIEUbLn7dx/XVHcEpxY5z2f/oSB9jGw8/6vxqRr6L7M25RCFRz7lCfLquQQAAA="
    },
    {
      "id": "family-room-bathroom",
      "label": "Family room bathroom",
      "src": "/images/family-room-bathroom-56bae8d0",
      "widths": [
        320,
        640,
        1024,
        1600,
        2400
      ],
      "width": 2400,
      "height": 1600,
      "blur": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAAAQBACdASoYABAAPu1iqU2ppaQiMAgBMB2JagCw7BuIJf29cYiXBrPheAD6chDMORpmlcIkWcfYgZR+JQ0waXyY9EzGIRPB/ZlPQwl9VU9vo5ym6hiPrNQkyzUniDJ8cIJ7yAL1+A7X4LLCHUFbL0enYNy1WDNILqSUvnVI+dbK4xlmYgBXdW/R6KOAAA=="
    },
    {
      "id": "family-room-study-table-1",
      "label": "Family room study table",
      "src": "/images/family-room-study-table-1-edd74b63",
      "widths": [
        320,
        640,
        1024,
        1600,
        2400
      ],
      "width": 2400,
      "height": 1600,
      "blur": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAACwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JbACdMoR3ACkF1NmmkWv+2ERUppegAP60l2560Y9d1MwDbNz/C+gBqmpzQeDzHBSsMAz7fSVkA/P4i/2Yhy9Javf55ZG/GsQl0lck9N8YsoGzlXssN/uDVXOphWUurgu5zayyz0C6Jk6R0Q1dEG1N/RMKeafjaxavcB9e6drE0AlMZzJ0OAAAAAA="
    },
    {
      "id": "family-room-study-table-2",
      "label": "Family room study table",
      "src": "/images/family-room-study-table-2-08fb69c0",
      "widths": [
        320,
        640,
        1024,
        1600,
        2400
      ],
      "width": 2400,
      "height": 1600,
      "blur": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAACQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JbACw7B4JRLz67/ZRTTOgh/arjAAA/fXsaHu/UXtDtBgYPa47HbedGzw6edLjtPWhC3R2EVvEctekuK3ukunxMS5Em3b8laZznjmirbEcGeJLWr6kJ68u4/O8SOlhpfjZlnbiMIK3/4IMSDP7zGZwRRAsTAAA"
    }
  ],
  "premium-suite": [
    {
      "id": "premium-suite",
      "label": "Premium suite",
      "src": "/images/premium-suite-22838b0b",
      "widths": [
        320,
        640,
        1024,
        1600,
        2400
      ],
      "width": 2400,
      "height": 1600,
      "blur": "data:image/webp;base64,UklGRq4AAABXRUJQVlA4IKIAAABwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JYwC1CMgCPMgYwWgpg6KqDZNrgADidh2Tv6ZsFrerrKJpEH4mejaUh71+PE8TOXq1aN9WzJX0yR0HfyaaCwm1pkeuLNmMkv+GGfIMa15Sf10tKb2ys0iDMge155hk0ygZ1Df0dojsB+r2KVqfYA7bF/tb3oPfsbdFLf7SU8L9gmuOaFgkB8f6IAA="
    },
    {
      "id": "premium-suite-bathroom-1",
      "label": "Premium suite bathroom",
      "src": "/images/premium-suite-bathroom-1-abc1f58b",
      "widths": [
        320,
        640,
        1024,
        1600,
        2400
      ],
      "width": 2400,
      "height": 3600,
      "blur": "data:image/webp;base64,UklGRugAAABXRUJQVlA4INwAAABQBgCdASoYACQAPu1oq1GppaOiqrgKATAdiWcAzBwizfW5jnvVCQn5ufdj1Pg3Jq5pDFOVODeUP+7aAAD+4YLmAqXpnLTBYr9FHxCgLil75YVSEMJ9h+bdgNGCI3LBRv627KED348Qwk+Sw5MKEovqiUZ6g9x8D1EBMGiSxB2c9XSRypUOkqcsA1fCICve80ozpny54scuIGk0UFsYEwV/nu/zhbuOONXcUJ+HpywxAzuDv0R99eH7p+WwTidrsWj9UyRCWMdM3uZe2fHxO7q3q0fwuGqpZ/vM8EgA"
    },
    {
      "id": "premium-suite-bathroom-2",
      "label": "Premium suite bathroom",
      "src": "/images/premium-suite-bathroom-2-d39a7efc",
      "widths": [
        320,
        640,
        1024,
        1600,
        2400
      ],
      "width": 2400,
      "height": 1600,
      "blur": "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAADwAwCdASoYABAAPu1iqU2ppaOiMAgBMB2JZwAAQvVwb8ze1tMQulEAAP61Iudb9mEN09432x+ql5+xGsHKCVoXzpDOpHcIHP3t9P1BfZPLR/CoSVbRSKPBa7rmWjVhD4ohBJUcRG33Gpi0qr7jVcVL8SvH3uZlllfmftfhQAA="
    },
    {
      "id": "premium-suite-study-table-1",
      "label": "Premium suite study table",
      "src": "/images/premium-suite-study-table-1-4611cf49",
      "widths": [
        320,
        640,
        1024,
        1600,
        2400
      ],
      "width": 2400,
      "height": 1600,
      "blur": "data:image/webp;base64,UklGRrIAAABXRUJQVlA4IKYAAAAwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JYwDE2CFU2Yz4JV7l3asUwqAA/m0WoPJWtVYQ+Ie/GY5qMtD5qJwz2qj8RbcXCqK55yauUSEqLipztdVjL2J7ZQpqMzrV08sqjFV7W/ZUEmNwfwb/t3+RvSNfjv6TjcjQe7lidqh00qfKvtGwUK+t0SruwwPeRdeWOtewy4Se+QHNBGmHxBkftbYLSCwA"
    }
  ],
  "twin-room": [
    {
      "id": "twin-room-1",
      "label": "Twin room",
      "src": "/images/twin-room-1-205aee84",
      "widths": [
        320,
        640,
        1024,
        1600,
        2400
      ],
      "width": 2400,
      "height": 1600,
      "blur": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAADwBACdASoYABAAPu1iqU2ppaOiMAgBMB2JagCdMoR3Ir+AmiCZQ02AXJ5T5dFVIHAA4lbU7xxX05LtLFebI7HOr1VPXKx5qxzQuaikmPM9WqSKkv+viATktSHzijZMA0YdR8C84Er66ZL/pjZMCWMAsYudp3IF/Db0x/IlFBhuM4lPCputjzVEuqjs/c8Q+Nhep0AviCeAAA=="
    },
    {
      "id": "twin-room-2",
      "label": "Twin room",
      "src": "/images/twin-room-2-7f94bd1c",
      "widths": [
        320,
        640,
        1024,
        1600,
        2400
      ],
      "width": 2400,
      "height": 1600,
      "blur": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAABQBACdASoYABAAPu1iqU2ppaOiMAgBMB2JaACdAB6s1QnlXUHa6FR7WOMAAP5kAa6IlD8bJ/MatviHksGfTQgqIjkawe2e4sb/QtaPV2Xcj3ZOyaXUa2sSG7KQjul1xc2VQxFA2UCes0xpfZ4Tu5rZcxFp+qRFQweQ0zelMHg0HK7MJi1kA/5JMpoJwtRTgAA="
    },
    {
      "id": "twin-room-bathroom-1",
      "label": "Twin room bathroom",
      "src": "/images/twin-room-bathroom-1-90568c56",
      "widths": [
        320,
        640,
        1024,
        1600,
        2400
      ],
      "width": 2400,
      "height": 1600,
      "blur": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAADwAwCdASoYABAAPu1iqU2ppaQiMAgBMB2JaACdABBKFLNhRcfnudBAAP0lCaz0QVCPl4g/qn0xiDqv3KNIMnTK6xqp6iG6JmIFkkmKfRt12P9Hvf/1WyZtt3fOH0+N5+nQIu2BBHG87jiZGWgDOl0CKSkgNohoV2AaD53o9if0wXLGT8I284LxTAA="
    },
    {
      "id": "twin-room-bathroom-2",
      "label": "Twin room bathroom",
      "src": "/images/twin-room-bathroom-2-98999431",
      "widths": [
        320,
        640,
        1024,
        1600,
        2400
      ],
      "width": 2400,
      "height": 1600,
      "blur": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAADwAwCdASoYABAAPu1iqU2ppaOiMAgBMB2JZgCdABgt7tR2lIqd4roAAPub8wZMdvFepbBLBmd1hW8JYPBnY7+R6PZ8t4a4R+dJR1tAikwhsbDQs33ooviT3BZkuWwUKpHVi4Sn8Ip0EVt5jAPBB3spDN9bUAAA"
    }
  ]
};
