// Usage: npm run images
// Reads originals from home_stay_original_photos/, writes responsive WebP files to public/images/
// and a typed manifest to src/modules/marketing/data/images.generated.ts.
import { createHash } from 'node:crypto';
import { existsSync } from 'node:fs';
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const sourceDir = path.join(root, 'home_stay_original_photos');
const outputDir = path.join(root, 'public', 'images');
const manifestPath = path.join(root, 'src', 'modules', 'marketing', 'data', 'images.generated.ts');

const WIDTHS = [320, 640, 1024, 1600, 2400];
const WEBP_QUALITY = 85;
const SOURCE_EXTENSIONS = new Set(['.jpg', '.jpeg', '.png', '.webp']);

// "Double_Bedroom_Bathroom_1.JPG" -> group "double-bedroom"; "About_Home_Stay.JPG" -> "about-home-stay"
function groupOf(id) {
  return id.match(/^(.*?)(?:-(?:bathroom|study-table))?(?:-\d+)?$/)[1];
}

function labelOf(id) {
  return id
    .replace(/-\d+$/, '')
    .split('-')
    .map((word, index) => (index === 0 ? word[0].toUpperCase() + word.slice(1) : word))
    .join(' ');
}

async function processImage(file) {
  const input = path.join(sourceDir, file);
  const buffer = await readFile(input);
  // Quality is part of the hash so changing it regenerates files instead of reusing old ones.
  const hash = createHash('sha1').update(buffer).update(String(WEBP_QUALITY)).digest('hex').slice(0, 8);
  const id = path.parse(file).name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  const base = `${id}-${hash}`;

  const meta = await sharp(buffer).metadata();
  const swap = (meta.orientation ?? 1) >= 5;
  const fullWidth = swap ? meta.height : meta.width;
  const fullHeight = swap ? meta.width : meta.height;

  const widths = WIDTHS.filter((w) => w < fullWidth);
  widths.push(Math.min(fullWidth, WIDTHS.at(-1)));
  const uniqueWidths = [...new Set(widths)].sort((a, b) => a - b);

  const written = [];
  for (const width of uniqueWidths) {
    const name = `${base}-${width}.webp`;
    written.push(name);
    if (existsSync(path.join(outputDir, name))) continue;
    await sharp(buffer)
      .rotate()
      .resize({ width, withoutEnlargement: true })
      .webp({ quality: WEBP_QUALITY })
      .toFile(path.join(outputDir, name));
  }

  const blurBuffer = await sharp(buffer).rotate().resize({ width: 24 }).webp({ quality: 40 }).toBuffer();
  const height = Math.round((fullHeight / fullWidth) * uniqueWidths.at(-1));

  return {
    group: groupOf(id),
    files: written,
    asset: {
      id,
      label: labelOf(id),
      src: `/images/${base}`,
      widths: uniqueWidths,
      width: uniqueWidths.at(-1),
      height,
      blur: `data:image/webp;base64,${blurBuffer.toString('base64')}`,
    },
  };
}

if (!existsSync(sourceDir)) {
  console.error(`Source folder not found: ${sourceDir}`);
  process.exit(1);
}

await mkdir(outputDir, { recursive: true });

const sources = (await readdir(sourceDir))
  .filter((file) => SOURCE_EXTENSIONS.has(path.extname(file).toLowerCase()))
  .sort((a, b) =>
    path.parse(a).name.localeCompare(path.parse(b).name, 'en', { numeric: true, sensitivity: 'base' }),
  );

const groups = {};
const keep = new Set();
for (const file of sources) {
  const { group, files, asset } = await processImage(file);
  (groups[group] ??= []).push(asset);
  files.forEach((name) => keep.add(name));
  console.log(`${file} -> ${files.length} sizes`);
}

// Remove outputs of deleted or replaced originals.
for (const name of await readdir(outputDir)) {
  if (!keep.has(name)) {
    await rm(path.join(outputDir, name));
    console.log(`removed stale ${name}`);
  }
}

const manifest = `// Generated by scripts/optimize-images.mjs. Do not edit; run \`npm run images\`.
import type { ImageAsset } from '../types';

export const imageManifest: Record<string, ImageAsset[]> = ${JSON.stringify(groups, null, 2)};
`;
await writeFile(manifestPath, manifest);
console.log(`Wrote ${sources.length} images in ${Object.keys(groups).length} groups.`);
